<testsuite errors="0" failures="0" tests="4" skipped="0" name="org.elasticsearch.recovery.RelocationIT" hostname="nohost.nodomain" time="8.493" timestamp="2016-04-18T03:03:08">
   <properties class="java.util.ArrayList">
      <property name="awt.toolkit" value="sun.lwawt.macosx.LWCToolkit"/>
      <property name="es.logger.level" value="WARN"/>
      <property name="file.encoding" value="UTF-8"/>
      <property name="file.encoding.pkg" value="sun.io"/>
      <property name="file.separator" value="/"/>
      <property name="ftp.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
      <property name="gopherProxySet" value="false"/>
      <property name="http.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
      <property name="java.awt.graphicsenv" value="sun.awt.CGraphicsEnvironment"/>
      <property name="java.awt.headless" value="true"/>
      <property name="java.awt.printerjob" value="sun.lwawt.macosx.CPrinterJob"/>
      <property name="java.class.path" value="/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/classes/test:/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/resources/test:/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/classes/main:/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/resources/main:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-core/5.5.0-snapshot-1721183/f6854c65c7f4c6d9de583f4daa4fd3ae8a3800f1/lucene-core-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-common/5.5.0-snapshot-1721183/69e187ef1d2d9c9570363eb4186821e0341df5b8/lucene-analyzers-common-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-backward-codecs/5.5.0-snapshot-1721183/fa00a45ff9bc6a4df44db81f2e4e44ea94bf88e/lucene-backward-codecs-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-grouping/5.5.0-snapshot-1721183/e996e6c723eb415ba2cfa7f5e98bbf194a4918dd/lucene-grouping-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-highlighter/5.5.0-snapshot-1721183/3b7a5d97b10885f16eb53deb15d64c942b9f9fdb/lucene-highlighter-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-join/5.5.0-snapshot-1721183/e4dda3eeb76e340aa4713a3b20d68c4a1504e505/lucene-join-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-memory/5.5.0-snapshot-1721183/800442a5d7612ce4c8748831871b4d436a50554e/lucene-memory-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-misc/5.5.0-snapshot-1721183/bdf184de9b5773c7af3ae908af78eeb1e512470c/lucene-misc-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queries/5.5.0-snapshot-1721183/fc59de52bd2c7e420edfd235723cb8b0dd44e92d/lucene-queries-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queryparser/5.5.0-snapshot-1721183/1d341e6a4f11f3170773ccffdbe6815b45967e3d/lucene-queryparser-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-sandbox/5.5.0-snapshot-1721183/a1b02c2b595ac92f45f0d2be03841a3a7fcae1f1/lucene-sandbox-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial/5.5.0-snapshot-1721183/e3ea422b56734329fb6974e9cf9f66478adb5793/lucene-spatial-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial3d/5.5.0-snapshot-1721183/5eadbd4e63120b59ab6445e39489205f98420471/lucene-spatial3d-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-suggest/5.5.0-snapshot-1721183/a336287e65d082535f02a8427666dbe46b1b9b74/lucene-suggest-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securesm/1.0/c0c6cf986ba0057390bfcc80c366a0e3157f944b/securesm-1.0.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.3.1/1303efbc4b181e5a58bf2e967dc156a3132b97c0/commons-cli-1.3.1.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.carrotsearch/hppc/0.7.1/8b5057f74ea378c0150a1860874a3ebdcb713767/hppc-0.7.1.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.8.2/d27c24204c5e507b16fec01006b3d0f1ec42aed4/joda-time-2.8.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.joda/joda-convert/1.2/35ec554f0cd00c956cc69051514d9488b1374dec/joda-convert-1.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.6.2/123f29333b2c6b3516b14252b6e93226bfcd6e37/jackson-core-2.6.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/2.6.2/395d18c1a1dd730b8026ee59c4067e5d2b45ba6e/jackson-dataformat-smile-2.6.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.6.2/4ae23088dd3fae47c66843f2e4251d7255ee140e/jackson-dataformat-yaml-2.6.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor/2.6.2/1e13c575f914c83761bb8e2aca7dfd9e4c647579/jackson-dataformat-cbor-2.6.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/io.netty/netty/3.10.5.Final/9ca7d55d246092bddd29b867706e2f6c7db701a0/netty-3.10.5.Final.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.tdunning/t-digest/3.0/84ccf145ac2215e6bfa63baa3101c0af41017cfc/t-digest-3.0.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.hdrhistogram/HdrHistogram/2.1.6/7495feb7f71ee124bd2a7e7d83590e296d71d80e/HdrHistogram-2.1.6.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.spatial4j/spatial4j/0.5/6e16edaf6b1ba76db7f08c2f3723fce3b358ecc3/spatial4j-0.5.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.vividsolutions/jts/1.13/3ccfb9b60f04d71add996a666ceb8902904fd805/jts-1.13.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/log4j/log4j/1.2.17/5af35056b4d257e4b64b9e8069c0746e8b08629f/log4j-1.2.17.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/log4j/apache-log4j-extras/1.2.17/85863614d82185d7e51fe21c00aa9117a523a8b6/apache-log4j-extras-1.2.17.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.6.2/8619e95939167fb37245b5670135e4feb0ec7d50/slf4j-api-1.6.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/4.1.0/1c12d070e602efd8021891cdd7fd18bc129372d4/jna-4.1.0.jar:/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/test/framework/build/libs/framework-3.0.0-SNAPSHOT.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.carrotsearch.randomizedtesting/randomizedtesting-runner/2.3.2/307965917fe8a22b7ee72deba39ef4b8e6ebc069/randomizedtesting-runner-2.3.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/junit/junit/4.11/4e031bb61df09069aeb2bffb4019e7a5034a4ee0/junit-4.11.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-all/1.3/63a21ebc981131004ad02e0434e799fd7f3a8d5a/hamcrest-all-1.3.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-test-framework/5.5.0-snapshot-1721183/a8d851d0ad82182b3a02f4b30c336e7aa0e173cb/lucene-test-framework-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-codecs/5.5.0-snapshot-1721183/8aa59442b028c7a2c1a516accb6142a8910ba5fc/lucene-codecs-5.5.0-snapshot-1721183.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.3.6/4c47155e3e6c9a41a28db36680b828ced53b8af4/httpclient-4.3.6.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.3.3/f91b7a4aadc5cf486df6e4634748d7dd7a73f06d/httpcore-4.3.3.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.1.3/f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f/commons-logging-1.1.3.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.10/4b95f4897fa13f2cd904aee711aeafc0c5295cd8/commons-codec-1.10.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar:/Users/lwiskowski/.gradle/caches/modules-2/files-2.1/com.carrotsearch.randomizedtesting/junit4-ant/2.3.2/dc8f03f6111974092491f35b8269eb0fc57f52f7/junit4-ant-2.3.2.jar"/>
      <property name="java.class.version" value="52.0"/>
      <property name="java.endorsed.dirs" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/endorsed"/>
      <property name="java.ext.dirs" value="/Users/lwiskowski/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"/>
      <property name="java.home" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre"/>
      <property name="java.io.tmpdir" value="./temp"/>
      <property name="java.library.path" value="/Users/lwiskowski/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:."/>
      <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
      <property name="java.runtime.version" value="1.8.0_71-b15"/>
      <property name="java.specification.name" value="Java Platform API Specification"/>
      <property name="java.specification.vendor" value="Oracle Corporation"/>
      <property name="java.specification.version" value="1.8"/>
      <property name="java.vendor" value="Oracle Corporation"/>
      <property name="java.vendor.url" value="http://java.oracle.com/"/>
      <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
      <property name="java.version" value="1.8.0_71"/>
      <property name="java.vm.info" value="mixed mode"/>
      <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
      <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
      <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
      <property name="java.vm.specification.version" value="1.8"/>
      <property name="java.vm.vendor" value="Oracle Corporation"/>
      <property name="java.vm.version" value="25.71-b15"/>
      <property name="junit4.childvm.count" value="4"/>
      <property name="junit4.childvm.cwd" value="/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0"/>
      <property name="junit4.childvm.id" value="0"/>
      <property name="junit4.memory.total" value="514850816"/>
      <property name="junit4.pidString" value="3684@host238-95.aruba.fit.edu"/>
      <property name="junit4.processors" value="8"/>
      <property name="line.separator" value="
"/>
      <property name="os.arch" value="x86_64"/>
      <property name="os.name" value="Mac OS X"/>
      <property name="os.version" value="10.11.4"/>
      <property name="path.separator" value=":"/>
      <property name="socksNonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
      <property name="sun.arch.data.model" value="64"/>
      <property name="sun.boot.class.path" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/classes"/>
      <property name="sun.boot.library.path" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home/jre/lib"/>
      <property name="sun.cpu.endian" value="little"/>
      <property name="sun.cpu.isalist" value=""/>
      <property name="sun.io.unicode.encoding" value="UnicodeBig"/>
      <property name="sun.java.command" value="com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe -eventsfile /Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/temp/junit4-J0-20160418_030118_670.events @/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/temp/junit4-J0-20160418_030118_670.suites -stdin"/>
      <property name="sun.java.launcher" value="SUN_STANDARD"/>
      <property name="sun.jnu.encoding" value="UTF-8"/>
      <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
      <property name="sun.os.patch.level" value="unknown"/>
      <property name="tests.artifact" value="core"/>
      <property name="tests.ifNoTests" value="fail"/>
      <property name="tests.maven" value="true"/>
      <property name="tests.prefix" value="tests"/>
      <property name="tests.security.manager" value="true"/>
      <property name="tests.seed" value="AF876320E2D19F69"/>
      <property name="tests.task" value=":core:integTest"/>
      <property name="user.country" value="US"/>
      <property name="user.dir" value="/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0"/>
      <property name="user.home" value="/Users/lwiskowski"/>
      <property name="user.language" value="en"/>
      <property name="user.name" value="lwiskowski"/>
      <property name="user.timezone" value=""/>
   </properties>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testCancellationCleansTempFiles" time="0.479"/>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testRelocationWhileIndexingRandom" time="7.302"/>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testRelocationWhileRefreshing" time="0.21"/>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testSimpleRelocationNoIndexing" time="0.474"/>
   <system-out><![CDATA[[2016-04-18 03:03:09,034][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[40mb]
[2016-04-18 03:03:09,075][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[40mb]
[2016-04-18 03:03:09,112][DEBUG][org.elasticsearch.indices.recovery] [node_t2] using max_bytes_per_sec[20mb]
[2016-04-18 03:03:09,345][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] started recovery from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local], id [163]
[2016-04-18 03:03:09,346][TRACE][org.elasticsearch.indices.recovery] [node_t2] collecting local files for [test][0] [163]
[2016-04-18 03:03:09,346][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] starting recovery from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local]
[2016-04-18 03:03:09,346][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local], mark_as_relocated false
[2016-04-18 03:03:09,346][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [2] for recovery
[2016-04-18 03:03:09,351][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_0.si], does not exists in remote
[2016-04-18 03:03:09,351][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_0.cfs], does not exists in remote
[2016-04-18 03:03:09,351][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_0.cfe], does not exists in remote
[2016-04-18 03:03:09,351][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_1.cfe], does not exists in remote
[2016-04-18 03:03:09,351][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_1.si], does not exists in remote
[2016-04-18 03:03:09,351][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_1.cfs], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_2.si], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_2.cfs], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_2.cfe], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_3.si], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_3.cfe], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_3.cfs], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_4.cfe], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_4.cfs], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_4.si], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_5.cfs], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_5.cfe], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [_5.si], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering [segments_2], does not exists in remote
[2016-04-18 03:03:09,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]: recovering_files [19] with total_size [18.3kb], reusing_files [0] with total_size [0b]
[2016-04-18 03:03:09,373][WARN ][org.elasticsearch.indices.recovery] [node_t0] 0 Remote file corruption on node {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local], recovering name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]. local checksum OK
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,375][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] Got exception on recovery
RemoteTransportException[[node_t2][local[108]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[106]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,376][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] failing recovery from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local], id [163]. Send shard failure: [true]
[2016-04-18 03:03:09,376][WARN ][org.elasticsearch.indices.cluster] [node_t2] [[test][0]] marking and sending shard failed due to [failed recovery]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local] into {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[108]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t2][local[108]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[106]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,378][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] closing IndexOutput file [VerifyingIndexOutput(out=MockIndexOutputWrapper(RateLimitedIndexOutput(FSIndexOutput(path="/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0/temp/org.elasticsearch.recovery.RelocationIT_AF876320E2D19F69-001/tempDir-001/data/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-4109346870483420931]-HASH=[263FD1F9D66C]-cluster/nodes/2/indices/test/0/index/recovery.1460962989345.segments_2"))))]
[2016-04-18 03:03:09,378][WARN ][org.elasticsearch.cluster.action.shard] [node_t0] [test][0] received shard failed for [test][0], node[n7uNFryXSm-JyVC86StzNA], [R], v[3], s[INITIALIZING], a[id=qtwgVvwEQJ6bre5UWbwbVw], unassigned_info[[reason=REPLICA_ADDED], at[2016-04-18T07:03:09.336Z]], indexUUID [Fb5db5N6TOePhcp4bAgu6w], message [failed recovery], failure [RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local] into {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[108]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local] into {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[108]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t2][local[108]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[106]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,378][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._2.cfe]
[2016-04-18 03:03:09,381][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._4.cfe]
[2016-04-18 03:03:09,382][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._1.si]
[2016-04-18 03:03:09,382][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._2.si]
[2016-04-18 03:03:09,384][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345.segments_2]
[2016-04-18 03:03:09,384][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._0.si]
[2016-04-18 03:03:09,385][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._1.cfe]
[2016-04-18 03:03:09,385][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._4.si]
[2016-04-18 03:03:09,385][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._3.si]
[2016-04-18 03:03:09,386][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._5.si]
[2016-04-18 03:03:09,386][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._3.cfe]
[2016-04-18 03:03:09,386][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._5.cfe]
[2016-04-18 03:03:09,386][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1460962989345._0.cfe]
[2016-04-18 03:03:09,392][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local], id [164]
[2016-04-18 03:03:09,393][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [164]
[2016-04-18 03:03:09,393][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local]
[2016-04-18 03:03:09,393][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local], mark_as_relocated false
[2016-04-18 03:03:09,393][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [2] for recovery
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_0.si], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_0.cfs], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_0.cfe], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_1.cfe], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_1.si], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_1.cfs], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_2.si], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_2.cfs], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_2.cfe], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_3.si], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_3.cfe], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_3.cfs], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_4.cfe], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_4.cfs], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_4.si], does not exists in remote
[2016-04-18 03:03:09,397][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_5.cfs], does not exists in remote
[2016-04-18 03:03:09,398][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_5.cfe], does not exists in remote
[2016-04-18 03:03:09,398][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [_5.si], does not exists in remote
[2016-04-18 03:03:09,398][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering [segments_2], does not exists in remote
[2016-04-18 03:03:09,398][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]: recovering_files [19] with total_size [18.3kb], reusing_files [0] with total_size [0b]
[2016-04-18 03:03:09,421][WARN ][org.elasticsearch.indices.recovery] [node_t0] 0 Remote file corruption on node {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local], recovering name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]. local checksum OK
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,422][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] Got exception on recovery
RemoteTransportException[[node_t1][local[107]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[106]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,423][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] failing recovery from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local], id [164]. Send shard failure: [true]
[2016-04-18 03:03:09,423][WARN ][org.elasticsearch.indices.cluster] [node_t1] [[test][0]] marking and sending shard failed due to [failed recovery]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local] into {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[107]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t1][local[107]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[106]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,425][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] closing IndexOutput file [VerifyingIndexOutput(out=MockIndexOutputWrapper(FSIndexOutput(path="/Users/lwiskowski/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0/temp/org.elasticsearch.recovery.RelocationIT_AF876320E2D19F69-001/tempDir-001/data/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-4109346870483420931]-HASH=[263FD1F9D66C]-cluster/nodes/1/indices/test/0/index/recovery.1460962989392.segments_2")))]
[2016-04-18 03:03:09,426][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._1.cfe]
[2016-04-18 03:03:09,426][WARN ][org.elasticsearch.cluster.action.shard] [node_t0] [test][0] received shard failed for [test][0], node[Sufw5RQCTUWuLrNeXc4A4A], [R], v[5], s[INITIALIZING], a[id=KroTsgNNTLCMGdnGQjntLQ], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-04-18T07:03:09.383Z], details[failed recovery, failure RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local] into {node_t2}{n7uNFryXSm-JyVC86StzNA}{local}{local[108]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[108]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]], indexUUID [Fb5db5N6TOePhcp4bAgu6w], message [failed recovery], failure [RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local] into {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[107]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{fuRqmeerR-GQ54Ehi7su9A}{local}{local[106]}[mode=>local] into {node_t1}{Sufw5RQCTUWuLrNeXc4A4A}{local}{local[107]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[107]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t1][local[107]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [19] files with total size of [18.3kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[106]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=tb483a actual=m3g33h (resource=name [segments_2], length [505], checksum [tb483a], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-04-18 03:03:09,426][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._4.cfe]
[2016-04-18 03:03:09,427][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392.segments_2]
[2016-04-18 03:03:09,428][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._0.si]
[2016-04-18 03:03:09,429][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._2.cfe]
[2016-04-18 03:03:09,429][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._0.cfe]
[2016-04-18 03:03:09,430][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._3.si]
[2016-04-18 03:03:09,430][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._3.cfe]
[2016-04-18 03:03:09,430][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._5.si]
[2016-04-18 03:03:09,430][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._4.si]
[2016-04-18 03:03:09,431][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._2.si]
[2016-04-18 03:03:09,432][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._5.cfe]
[2016-04-18 03:03:09,432][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1460962989392._1.si]
[2016-04-18 03:03:09,506][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[40mb]
[2016-04-18 03:03:09,549][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[188mb]
[2016-04-18 03:03:09,561][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local], id [165]
[2016-04-18 03:03:09,561][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [165]
[2016-04-18 03:03:09,563][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local]
[2016-04-18 03:03:09,563][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local], mark_as_relocated false
[2016-04-18 03:03:09,563][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-04-18 03:03:09,564][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-04-18 03:03:09,564][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-04-18 03:03:09,569][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: prepare remote engine for translog
[2016-04-18 03:03:09,575][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: remote engine start took [6ms]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: took [0s]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [0]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: sending transaction log operations
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] no translog operations to send to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [0][0b] (total: [0]) translog operations to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: took [120.2micros]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: took [251.9micros]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local] as done, id [165]
[2016-04-18 03:03:09,576][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local], took[14ms]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [6ms]
         : recovered [0] transaction log operations, took [0s]

[2016-04-18 03:03:09,609][DEBUG][org.elasticsearch.indices.recovery] [node_t2] using max_bytes_per_sec[79mb]
[2016-04-18 03:03:12,674][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] started recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local], id [166]
[2016-04-18 03:03:12,674][TRACE][org.elasticsearch.indices.recovery] [node_t2] collecting local files for [test][0] [166]
[2016-04-18 03:03:12,687][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] starting recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local]
[2016-04-18 03:03:12,687][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local], mark_as_relocated false
[2016-04-18 03:03:12,687][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-04-18 03:03:12,690][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-04-18 03:03:12,690][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-04-18 03:03:12,711][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: prepare remote engine for translog
[2016-04-18 03:03:12,723][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: remote engine start took [12ms]
[2016-04-18 03:03:12,723][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: took [0s]
[2016-04-18 03:03:12,723][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [2114]
[2016-04-18 03:03:12,724][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: sending transaction log operations
[2016-04-18 03:03:13,587][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [2114][496.9kb] (total: [2114]) translog operations to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]
[2016-04-18 03:03:13,588][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: took [863.8ms]
[2016-04-18 03:03:13,588][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]
[2016-04-18 03:03:13,855][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t2}{SImtbf77T7OnHD9NVIWoug}{local}{local[115]}[mode=>local]: took [267.1ms]
[2016-04-18 03:03:13,855][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] marking recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local] as done, id [166]
[2016-04-18 03:03:13,855][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] recovery completed from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local], took[1.1s]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [12ms]
         : recovered [2114] transaction log operations, took [863ms]

[2016-04-18 03:03:13,882][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local], id [167]
[2016-04-18 03:03:13,882][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [167]
[2016-04-18 03:03:13,884][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local]
[2016-04-18 03:03:13,884][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local], mark_as_relocated false
[2016-04-18 03:03:13,885][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-04-18 03:03:13,888][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-04-18 03:03:13,888][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-04-18 03:03:13,892][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: prepare remote engine for translog
[2016-04-18 03:03:13,897][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: remote engine start took [4.9ms]
[2016-04-18 03:03:13,897][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: took [0s]
[2016-04-18 03:03:13,897][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [2764]
[2016-04-18 03:03:13,897][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: sending transaction log operations
[2016-04-18 03:03:14,415][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent batch of [2182][512kb] (total: [2765]) translog operations to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]
[2016-04-18 03:03:14,508][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [583][140.1kb] (total: [2765]) translog operations to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]
[2016-04-18 03:03:14,508][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: took [610.9ms]
[2016-04-18 03:03:14,508][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]
[2016-04-18 03:03:15,049][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{I1AOmSAmROaFptiZPSRjoQ}{local}{local[114]}[mode=>local]: took [541ms]
[2016-04-18 03:03:15,049][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local] as done, id [167]
[2016-04-18 03:03:15,050][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{0zYRqN4GQZuo-wHI1sSvfw}{local}{local[112]}[mode=>local], took[1.1s]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [4ms]
         : recovered [2765] transaction log operations, took [610ms]

[2016-04-18 03:03:16,813][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[93mb]
[2016-04-18 03:03:16,859][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[65mb]
[2016-04-18 03:03:16,887][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{ZqH1vllJSVipql8u8oxE1g}{local}{local[118]}[mode=>local], id [168]
[2016-04-18 03:03:16,887][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [168]
[2016-04-18 03:03:16,887][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{ZqH1vllJSVipql8u8oxE1g}{local}{local[118]}[mode=>local]
[2016-04-18 03:03:16,887][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local], mark_as_relocated false
[2016-04-18 03:03:16,887][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-04-18 03:03:16,888][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-04-18 03:03:16,888][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-04-18 03:03:16,892][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: prepare remote engine for translog
[2016-04-18 03:03:16,895][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: remote engine start took [3.7ms]
[2016-04-18 03:03:16,895][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: took [0s]
[2016-04-18 03:03:16,895][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [0]
[2016-04-18 03:03:16,895][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: sending transaction log operations
[2016-04-18 03:03:16,896][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] no translog operations to send to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]
[2016-04-18 03:03:16,896][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [0][0b] (total: [0]) translog operations to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]
[2016-04-18 03:03:16,896][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: took [168.5micros]
[2016-04-18 03:03:16,896][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]
[2016-04-18 03:03:16,896][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{FRxw8ikaQoabGazs-eSZMQ}{local}{local[119]}[mode=>local]: took [206.6micros]
[2016-04-18 03:03:16,896][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{ZqH1vllJSVipql8u8oxE1g}{local}{local[118]}[mode=>local] as done, id [168]
[2016-04-18 03:03:16,896][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{ZqH1vllJSVipql8u8oxE1g}{local}{local[118]}[mode=>local], took[9ms]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [3ms]
         : recovered [0] transaction log operations, took [0s]

[2016-04-18 03:03:17,019][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[160mb]
[2016-04-18 03:03:17,211][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[157mb]
[2016-04-18 03:03:17,226][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{m4RFCVyVStC7m_cls8TWCw}{local}{local[122]}[mode=>local], id [169]
[2016-04-18 03:03:17,226][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [169]
[2016-04-18 03:03:17,247][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{m4RFCVyVStC7m_cls8TWCw}{local}{local[122]}[mode=>local]
[2016-04-18 03:03:17,247][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local], mark_as_relocated false
[2016-04-18 03:03:17,247][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [2] for recovery
[2016-04-18 03:03:17,262][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: recovering [_0.cfe], does not exists in remote
[2016-04-18 03:03:17,262][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: recovering [_0.si], does not exists in remote
[2016-04-18 03:03:17,262][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: recovering [_0.cfs], does not exists in remote
[2016-04-18 03:03:17,262][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: recovering [segments_2], does not exists in remote
[2016-04-18 03:03:17,263][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: recovering_files [4] with total_size [3.4kb], reusing_files [0] with total_size [0b]
[2016-04-18 03:03:17,355][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: prepare remote engine for translog
[2016-04-18 03:03:17,366][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: remote engine start took [11ms]
[2016-04-18 03:03:17,366][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: took [0s]
[2016-04-18 03:03:17,366][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [10]
[2016-04-18 03:03:17,366][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: sending transaction log operations
[2016-04-18 03:03:17,380][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [10][440b] (total: [10]) translog operations to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]
[2016-04-18 03:03:17,380][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: took [14.1ms]
[2016-04-18 03:03:17,380][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]
[2016-04-18 03:03:17,430][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{RGHgninERiiE5FfXPeIQhA}{local}{local[124]}[mode=>local]: took [50ms]
[2016-04-18 03:03:17,431][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{m4RFCVyVStC7m_cls8TWCw}{local}{local[122]}[mode=>local] as done, id [169]
[2016-04-18 03:03:17,431][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{m4RFCVyVStC7m_cls8TWCw}{local}{local[122]}[mode=>local], took[204ms]
   phase1: recovered_files [4] with total_size of [3.4kb], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [11ms]
         : recovered [10] transaction log operations, took [14ms]

]]></system-out>
   <system-err><![CDATA[]]></system-err>
</testsuite>